# syntax=docker/dockerfile:1.6
FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY tsconfig.json ./
COPY bot ./bot
COPY src ./src
ENV NODE_ENV=production
CMD ["npm", "run", "bot"]
